package pinak.sppunotify.util

import android.content.Context
import android.graphics.pdf.PdfDocument
import android.net.Uri
import androidx.core.content.FileProvider
import pinak.sppunotify.data.local.ResultEntity
import java.io.File
import java.io.FileOutputStream

object ResultPdfExport {

    fun exportToPdf(context: Context, result: ResultEntity): Uri? {
        val pdfDocument = PdfDocument()
        
        // A4 size in points (72 dpi)
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create()
        val page = pdfDocument.startPage(pageInfo)
        val canvas = page.canvas
        
        // Generate the premium card bitmap using the existing generator
        val bitmap = ResultImageGenerator.generateAndShare(context, result)?.let {
            // Need to read the file back to bitmap
            val file = File(context.cacheDir, "shared_images/result_${result.id}.png")
            if (file.exists()) {
                android.graphics.BitmapFactory.decodeFile(file.absolutePath)
            } else null
        }
        
        if (bitmap != null) {
            val scale = (canvas.width - 80f) / bitmap.width
            val scaledWidth = bitmap.width * scale
            val scaledHeight = bitmap.height * scale
            
            val left = (canvas.width - scaledWidth) / 2f
            val top = 60f
            
            canvas.drawBitmap(bitmap, null, android.graphics.RectF(left, top, left + scaledWidth, top + scaledHeight), null)
            
            // Add official footer
            val paint = android.graphics.Paint()
            paint.textSize = 12f
            paint.color = android.graphics.Color.GRAY
            canvas.drawText("Generated by SPPU Result Notify", 40f, canvas.height - 40f, paint)
            canvas.drawText("Official University Result Snapshot", canvas.width - 220f, canvas.height - 40f, paint)
        }

        pdfDocument.finishPage(page)
        
        val pdfFolder = File(context.cacheDir, "exported_pdfs")
        pdfFolder.mkdirs()
        val pdfFile = File(pdfFolder, "result_${result.id}.pdf")
        
        try {
            pdfDocument.writeTo(FileOutputStream(pdfFile))
            pdfDocument.close()
            return FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", pdfFile)
        } catch (e: Exception) {
            pdfDocument.close()
            return null
        }
    }
}
